[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
	autocmd FileType defx call s:defx_my_settings()
	autocmd BufWritePost * call defx#redraw()
	autocmd BufEnter * call defx#redraw()
	autocmd WinNew * call defx#redraw()

	nnoremap <silent>fs :Defx -vertical-preview -toggle<CR>

	call defx#custom#option('_', {
		\ 'show_ignored_files': 1,
		\ 'buffer_name': 'ðŸš€',
		\ 'toggle': 1,
		\ 'resume': 1,
		\ 'columns': 'space:indent:icons:space:filename:mark',
  \ })

	function! s:defx_my_settings() abort
		nnoremap <silent><buffer><expr> <CR>
			\ defx#is_directory() ?
			\ defx#do_action('open') :
			\ defx#do_action('multi', ['open', 'quit'])

		nnoremap <silent><buffer><expr> q
			\ defx#do_action('quit')

		nnoremap <silent><buffer><expr> n
			\ defx#do_action('new_file')

		nnoremap <silent><buffer><expr> D
			\ defx#do_action('remove')

		nnoremap <silent><buffer><expr> h
			\ defx#do_action('cd', ['..'])

		nnoremap <silent><buffer><expr> j
			\ line('.') == line('$') ? 'gg' : 'j'

		nnoremap <silent><buffer><expr> k
			\ line('.') == 1 ? 'G' : 'k'

		nnoremap <silent><buffer><expr> l
			\ defx#do_action('open')

		nnoremap <silent><buffer><expr> o
			\ defx#do_action('open_tree', 'toggle')

		nnoremap <silent><buffer><expr> O
			\ defx#do_action('close_tree')

		nnoremap <silent><buffer><expr> yy
			\ defx#do_action('yank_path')

		nnoremap <silent><buffer><expr> r
			\ defx#do_action('rename')

		nnoremap <silent><buffer><expr> i
			\ defx#do_action('drop', 'vsplit')

		nnoremap <silent><buffer><expr> ~
			\ defx#do_action('cd')

		nnoremap <silent><buffer><expr> K
			\ defx#do_action('preview')

		nnoremap <silent><buffer><expr> c
			\ defx#do_action('copy')

		nnoremap <silent><buffer><expr> p
			\ defx#do_action('paste')

		nnoremap <silent><buffer><expr> m
			\ defx#do_action('move')

    noremap <silent><buffer><expr> <Space>
			\ defx#do_action('toggle_select') . 'j'

    nnoremap <silent><buffer><expr> *
			\ defx#do_action('toggle_select_all')

	endfunction
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'
hook_add = '''

'''
